title: 망한 땅으로
description: 개짬통 OSR
remote_theme: just-the-docs/just-the-docs@v0.12.0

url: https://bipedalocto.github.io/ITTAL/

color_scheme: dark

head_include: custom.html

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
